[tool.poetry]
name = "beer-backend"
version = "0.1.0"
description = ""
authors = ["Edwin Fuentes <efuentesamin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
